# Spec v2 — pricing page overhaul, remaining pricing-model files, audit quick fixes.
P = ["pricing/index.html"]
PL = ["platform/index.html"]

SPECS = [
    # ═══ PRICING PAGE ═══
    dict(id="p-title", category="pricing", files=P, expect=(3, 4),
         find="Pricing — PropertyFlow | Free, 5% or 50/50 Partner",
         replace="Pricing — PropertyFlow | First 3 Free, £9.99 per Extra Property, or 50/50 Partner"),
    dict(id="p-metadesc", category="pricing", files=P, expect=(3, 3),
         find="Start free on one property, run the whole portfolio yourself at 5% of booking revenue, or hand the entire operation to us as a 50/50 Partner.",
         replace="Your first 3 properties are free. From your 4th, just £9.99 per extra property per month — or hand the entire operation to us as a 50/50 Partner."),
    dict(id="p-faq1-name", category="pricing", files=P, expect=(2, 2),
         find="Is Get Started really free?",
         replace="Is the Free plan really free?"),
    dict(id="p-faq1-ans", category="pricing", files=P, expect=(2, 2),
         find="Yes. You get the full PMS on one property with no card and no time limit. It is the best way to try PropertyFlow before you scale.",
         replace="Yes. You get the full PMS on up to 3 properties — £0 a month, forever, no card and no time limit. Airbnb bookings carry 0% commission, other OTAs 5%."),
    dict(id="p-faq2-name", category="pricing", files=P, expect=(2, 2),
         find="How does the 5% work on Full Management?",
         replace="How does Premium pricing work?"),
    dict(id="p-faq2-ans", category="pricing", files=P, expect=(2, 2),
         find="It is 5% of booking revenue, with no fixed or per-property fees. You add as many properties as you like and only pay when a booking earns.",
         replace="Your first 3 properties stay free. From your 4th, Premium is £9.99 per extra property per month — and your other-OTA commission drops from 5% to 3% (Airbnb stays 0%). It auto-upgrades only when needed."),
    dict(id="p-faq-move-ans", category="pricing", files=P, expect=(2, 2),
         find="Any time. Most operators start free, move to Full Management as they add properties, then apply to Partner when they want to go hands-free.",
         replace="Any time. Most operators start free, auto-upgrade to Premium as they grow past three properties, then apply to Partner when they want to go hands-free."),
    dict(id="p-hero-sub", category="pricing", files=P, expect=(1, 1),
         find="Start free, run the whole portfolio yourself for a simple percentage, or hand the entire operation to us.",
         replace="Start free on your first three properties, scale at a simple per-property price, or hand the entire operation to us."),
    dict(id="p-card1-name", category="pricing", files=P, expect=(1, 1),
         find='<h2 class="pricing-card__name">Get Started</h2>',
         replace='<h2 class="pricing-card__name">Free</h2>'),
    dict(id="p-card1-desc", category="pricing", files=P, expect=(1, 1),
         find='<p class="pricing-card__desc">Try the full PMS on one property.</p>',
         replace='<p class="pricing-card__desc">For solo hosts with 1–3 properties.</p>'),
    dict(id="p-card1-price", category="pricing", files=P, expect=(1, 1),
         find='<p class="pricing-card__price">Free</p>',
         replace='<p class="pricing-card__price">£0<span class="pricing-card__price-sub"> / month, forever</span></p>'),
    dict(id="p-card1-note", category="pricing", files=P, expect=(1, 1),
         find='<p class="pricing-card__note">1 property &middot; no card required</p>',
         replace='<p class="pricing-card__note">1–3 properties &middot; no card &middot; Airbnb 0%, other OTAs 5%</p>'),
    dict(id="p-card1-feat", category="pricing", files=P, expect=(1, 1),
         find="Full platform, one property",
         replace="Full platform, up to 3 properties"),
    dict(id="p-card2-name", category="pricing", files=P, expect=(1, 1),
         find='<h2 class="pricing-card__name">Full Management</h2>',
         replace='<h2 class="pricing-card__name">Premium</h2>'),
    dict(id="p-card2-desc", category="pricing", files=P, expect=(1, 1),
         find='<p class="pricing-card__desc">Run the whole portfolio on the PMS.</p>',
         replace='<p class="pricing-card__desc">For multi-property portfolios &middot; 4+ properties.</p>'),
    dict(id="p-card2-price", category="pricing", files=P, expect=(1, 1),
         find='<p class="pricing-card__price">5%<span class="pricing-card__price-sub"> of booking revenue</span></p>',
         replace='<p class="pricing-card__price">£9.99<span class="pricing-card__price-sub"> / extra property / month</span></p>'),
    dict(id="p-card2-note", category="pricing", files=P, expect=(1, 1),
         find='<p class="pricing-card__note">Unlimited properties &middot; pay only when you earn</p>',
         replace='<p class="pricing-card__note">First 3 always free &middot; Airbnb 0%, other OTAs 3%</p>'),
    dict(id="p-card2-feat", category="pricing", files=P, expect=(1, 1),
         find="Everything in Get Started",
         replace="Everything in Free"),
    dict(id="p-th-name1", category="pricing", files=P, expect=(1, 1),
         find='<div class="pricing-table__head-name">Get Started</div>',
         replace='<div class="pricing-table__head-name">Free</div>'),
    dict(id="p-th-price1", category="pricing", files=P, expect=(1, 1),
         find='<div class="pricing-table__head-price">Free</div>',
         replace='<div class="pricing-table__head-price">£0 / month</div>'),
    dict(id="p-th-name2", category="pricing", files=P, expect=(1, 1),
         find='<div class="pricing-table__head-name pricing-table__head-name--orange">Full Management</div>',
         replace='<div class="pricing-table__head-name pricing-table__head-name--orange">Premium</div>'),
    dict(id="p-th-price2", category="pricing", files=P, expect=(1, 1),
         find='<div class="pricing-table__head-price">5% of revenue</div>',
         replace='<div class="pricing-table__head-price">£9.99 / extra property</div>'),
    dict(id="p-tr-properties", category="pricing", files=P, expect=(1, 1),
         find='<div class="pricing-table__cell"><span class="pricing-table__txt">1</span></div>',
         replace='<div class="pricing-table__cell"><span class="pricing-table__txt">1–3</span></div>'),
    dict(id="p-mega-highlands-link", category="bugfix", files=P, expect=(1, 1),
         find='href="/for-landlords/" class="ds-mega__link"><span class="ds-mega__link-title">Highlands &amp; coast</span>',
         replace='href="/for-landlords/highlands-and-coast/" class="ds-mega__link"><span class="ds-mega__link-title">Highlands &amp; coast</span>'),

    # ═══ PLATFORM ═══
    dict(id="pl-metas", category="pricing", files=PL, expect=(2, 3),
         find="— free Get Started, Full Management at 5%, or Partner 50/50.",
         replace="— your first 3 properties free, £9.99 per extra property after that, or Partner 50/50."),
    dict(id="pl-lead", category="pricing", files=PL, expect=(1, 1),
         find="Try the full platform on one property for free, then run your whole portfolio for a simple 5% of booking revenue.",
         replace="Try the full platform free on up to three properties, then scale for just £9.99 per extra property per month."),
    dict(id="pl-hero-free", category="pricing", files=PL, expect=(1, 2),
         find="free to try on your first property",
         replace="free to try on your first three properties"),
    dict(id="pl-tier1-name", category="pricing", files=PL, expect=(1, 1),
         find='<h3 class="ds-tier__name">Get Started</h3>',
         replace='<h3 class="ds-tier__name">Free</h3>'),
    dict(id="pl-tier1-sub", category="pricing", files=PL, expect=(1, 1),
         find='<p class="ds-tier__sub">Try the full PMS on one property</p>',
         replace='<p class="ds-tier__sub">For solo hosts · 1–3 properties</p>'),
    dict(id="pl-tier1-price", category="pricing", files=PL, expect=(1, 1),
         find='<div class="ds-tier__price">Free <span>/ 1 property</span></div>',
         replace='<div class="ds-tier__price">£0 <span>/ month, forever</span></div>'),
    dict(id="pl-tier2-name", category="pricing", files=PL, expect=(1, 1),
         find='<h3 class="ds-tier__name">Full Management</h3>',
         replace='<h3 class="ds-tier__name">Premium</h3>'),
    dict(id="pl-tier2-sub", category="pricing", files=PL, expect=(1, 1),
         find='<p class="ds-tier__sub">Run everything yourself on the PMS</p>',
         replace='<p class="ds-tier__sub">For multi-property portfolios · 4+ properties</p>'),
    dict(id="pl-tier2-price", category="pricing", files=PL, expect=(1, 1),
         find='<div class="ds-tier__price">5% <span>of booking revenue</span></div>',
         replace='<div class="ds-tier__price">£9.99 <span>/ extra property / month</span></div>'),
    dict(id="pl-tier2-note", category="pricing", files=PL, expect=(1, 1),
         find='<p class="ds-tier__note">Unlimited properties, pay only when you earn</p>',
         replace='<p class="ds-tier__note">First 3 always free · Airbnb 0%, other OTAs 3%</p>'),
    dict(id="pl-cta-3props", category="pricing",
         files=["platform/channel-management/index.html", "platform/unified-inbox/index.html",
                "platform/compliance/index.html"], expect=(3, 3),
         find="Start free on your first property.",
         replace="Start free on your first three properties."),
    dict(id="pl-dbs-cta", category="pricing", files=["platform/direct-booking-site/index.html"], expect=(1, 1),
         find="Spin up your direct site free on your first property.",
         replace="Spin up your direct site free — your first three properties cost nothing."),
    dict(id="pl-mc-cta", category="pricing", files=["platform/multi-calendar/index.html"], expect=(1, 1),
         find="connect your first property's calendar in minutes",
         replace="connect your calendars in minutes"),

    # ═══ OTHER PAGES ═══
    dict(id="blog-clms-table", category="pricing", files=["blog/corporate-let-vs-managed-service/index.html"], expect=(2, 2),
         find='<td class="ds-table__cell">Get Started free / Full Management 5%</td>',
         replace='<td class="ds-table__cell">Free (1–3 properties) / Premium £9.99 per extra property</td>'),
    dict(id="fl-jso-desc", category="pricing", files=["for-landlords/index.html"], expect=(1, 1),
         find="Get Started free on one property, Full Management at 5% of revenue, or Partner 50/50.",
         replace="Your first 3 properties free, £9.99 per extra property after that, or Partner 50/50."),
    dict(id="fl-jso-threeways", category="pricing", files=["for-landlords/index.html"], expect=(1, 1),
         find="Get Started is free for a single property. Full Management is 5% of booking revenue across unlimited properties.",
         replace="The Free plan covers up to 3 properties, forever. Premium is £9.99 per extra property per month from your 4th — Airbnb at 0% commission, other OTAs at 3%."),
    dict(id="fl-hero", category="pricing", files=["for-landlords/index.html"], expect=(1, 1),
         find="Try the PMS free on one property. Run your whole portfolio yourself for 5% of booking revenue. Or become a verified Partner",
         replace="Try the PMS free on your first three properties. From your 4th, scale for just £9.99 per extra property per month. Or become a verified Partner"),
    dict(id="fl-cta", category="pricing", files=["for-landlords/index.html"], expect=(1, 1),
         find="Start free on one property today, or book a call and we'll help you choose between Full Management and a Partner arrangement.",
         replace="Start free with up to three properties today, or book a call and we'll help you choose between Premium and a Partner arrangement."),
    dict(id="fl-faq", category="pricing", files=["for-landlords/index.html"], expect=(1, 2),
         find="Get Started is a free trial of the PMS on one property. Full Management gives you the full platform across as many properties as you like for 5% of booking revenue, and you run the day-to-day yourself.",
         replace="The Free plan gives you the full PMS on up to 3 properties, forever. Premium unlocks unlimited properties at £9.99 per extra property per month from your 4th, and you run the day-to-day yourself."),
    dict(id="bp-metas", category="pricing", files=["for-landlords/building-a-portfolio/index.html"], expect=(2, 3),
         find="Run your whole portfolio yourself on the PMS for 5% of booking revenue, with no fixed fees and no per-property charge.",
         replace="Run your whole portfolio yourself on the PMS — your first 3 properties free, then £9.99 per extra property per month."),
    dict(id="bp-jsonld", category="pricing", files=["for-landlords/building-a-portfolio/index.html"], expect=(1, 1),
         find="Run a growing short-let portfolio yourself on the PMS for a flat 5% of booking revenue, with no fixed fees and no per-property charge.",
         replace="Run a growing short-let portfolio yourself on the PMS — first 3 properties free, then a flat £9.99 per extra property per month."),
    dict(id="bp-hero", category="pricing", files=["for-landlords/building-a-portfolio/index.html"], expect=(1, 1),
         find="Two, five, twenty. On Full Management you run the whole portfolio yourself on the PMS for 5% of booking revenue, with no fixed fees and no per-property charge.",
         replace="Two, five, twenty. On Premium you run the whole portfolio yourself on the PMS — your first 3 properties free, then £9.99 per extra property per month."),
    dict(id="jso-move-up", category="pricing", files=["for-landlords/just-starting-out/index.html"], expect=(1, 1),
         find="And move up to Full Management whenever you add your second.",
         replace="And move up to Premium only when you add your fourth."),
    dict(id="nps-move-up", category="pricing", files=["for-landlords/new-to-property-software/index.html"], expect=(2, 2),
         find="You move up to Full Management, or hand operations to us as a Partner.",
         replace="You move up to Premium, or hand operations to us as a Partner."),
    dict(id="fi-meta", category="pricing", files=["for-investors/index.html"], expect=(1, 1),
         find="Get Started free, Full Management at 5%, or Partner 50/50.",
         replace="First 3 properties free, £9.99 per extra property after that, or Partner 50/50."),
    dict(id="fi-faq", category="pricing", files=["for-investors/index.html"], expect=(1, 2),
         find="Three ways. Get Started is a free trial of the PMS on one property. Full Management runs your whole portfolio on the platform for 5% of booking revenue, self-operated.",
         replace="Three ways. The Free plan gives you the full PMS on up to 3 properties. Premium runs your whole portfolio from £9.99 per extra property per month, self-operated."),
    dict(id="fi-yield", category="pricing", files=["for-investors/index.html"], expect=(1, 2),
         find="On Full Management you pay 5% of booking revenue; the Partner model is",
         replace="On Premium you pay £9.99 per extra property per month; the Partner model is"),
    dict(id="em-pd-li", category="pricing", files=["edinburgh-market/pricing-data/index.html"], expect=(1, 1),
         find="Platform: Start free on one property with Get Started, scale on Full Management at 5% of booking revenue, or become a 50/50 Partner.",
         replace="Platform: your first 3 properties free, £9.99 per extra property per month after that, or become a 50/50 Partner."),
    dict(id="about-threeways", category="pricing", files=["about/index.html"], expect=(1, 1),
         find="One platform, three ways in: free to try, self-run for 5% of booking revenue, or a full 50/50 operational partnership.",
         replace="One platform, three ways in: free for your first three properties, self-run from £9.99 per extra property, or a full 50/50 operational partnership."),
    dict(id="contact-3props", category="pricing", files=["contact/index.html"], expect=(1, 1),
         find="run the full PMS on your first property.",
         replace="run the full PMS on your first three properties."),

    # ═══ QUICK FIXES (agent findings) ═══
    dict(id="founder-placeholder", category="bugfix", files=["index.html"], expect=(1, 1),
         find='<p class="ds-founder__name">[Founder name]</p>\n                <p class="ds-founder__role">Founder, PropertyFlow</p>',
         replace='<p class="ds-founder__role">Founder, PropertyFlow</p>'),
    dict(id="jsonld-logo-webp", category="bugfix", files=None, expect=(1, 12),
         find='"logo": "https://www.propertyflow.uk/images/logo.webp"',
         replace='"logo": "https://www.propertyflow.uk/favicon-512.png"'),
    dict(id="founding-date", category="bugfix", files=["index.html"], expect=(1, 1),
         find='"foundingDate": "2025"',
         replace='"foundingDate": "2025-12"'),
    dict(id="inquiry-enquiry", category="bugfix", files=None, expect=(1, 4),
         find="guest inquiry",
         replace="guest enquiry"),
    dict(id="ground-op-dash", category="bugfix", files=None, expect=(2, 8),
         find="every ground operation, linen, cleaning, changeovers",
         replace="every ground operation — linen, cleaning, changeovers"),
    dict(id="brand-title-suffix", category="bugfix", files=None, expect=(10, 30),
         find="| Property Flow</title>",
         replace="| PropertyFlow</title>"),
    dict(id="cognito-rename", category="bugfix", files=None, expect=(10, 25),
         find="Cognito Pricing",
         replace="Smart Pricing"),
    dict(id="careers-meta", category="bugfix", files=["careers/index.html"], expect=(1, 3),
         find="View open positions and apply today.",
         replace="Meet the team and introduce yourself — we hire ahead of the curve."),
    dict(id="about-meta-desc", category="bugfix", files=["about/index.html"], expect=(1, 3),
         find='content="About PropertyFlow — Compliance-First STL Management Platform for UK Operators | Company No. 16927756"',
         replace='content="The team and mission behind PropertyFlow — the compliance-first platform UK short-term let operators use to run channels, pricing, guest messaging and financials in one place."'),
    dict(id="str-stl-home", category="bugfix", files=["index.html"], expect=(1, 2),
         find="Active UK STR listings",
         replace="Active UK STL listings"),
    dict(id="str-stl-about", category="bugfix", files=["about/index.html"], expect=(1, 2),
         find="UK STR management",
         replace="UK STL management"),
    dict(id="str-stl-careers", category="bugfix", files=["careers/index.html"], expect=(1, 2),
         find="STR management careers",
         replace="STL management careers"),
    dict(id="contact-timezone", category="bugfix", files=["contact/index.html"], expect=(1, 1),
         find="Mon–Fri, 9:00–18:00 (UTC)",
         replace="Mon–Fri, 9:00–18:00 (UK time)"),
    dict(id="areaserved-city", category="bugfix", files=None, expect=(1, 3),
         find='"@type": "City", "name": "United Kingdom"',
         replace='"@type": "Country", "name": "United Kingdom"'),
    dict(id="compliance-nations", category="bugfix", files=["platform/compliance/index.html"], expect=(1, 1),
         find="4 nations",
         replace="4 regimes"),
    dict(id="compliance-epc", category="bugfix", files=["platform/compliance/index.html"], expect=(1, 1),
         find="EPC (min. Band E)",
         replace="EPC (where required)"),
    dict(id="blog-alarms-scope", category="bugfix", files=["blog/licensing-and-compliance/index.html"], expect=(1, 1),
         find="interlinked smoke and carbon-monoxide alarms",
         replace="smoke and carbon-monoxide alarms (interlinked in Scotland)"),
    dict(id="blog-safety-alarms", category="bugfix", files=["blog/safety-and-certificates/index.html"], expect=(1, 1),
         find="Interlinked, tested regularly",
         replace="Interlinked in Scotland; tested regularly"),
    dict(id="blog-epc-band", category="bugfix", files=["blog/licensing-and-compliance/index.html"], expect=(1, 1),
         find="an EPC of at least Band E in England and Wales",
         replace="a valid EPC where one is required in England and Wales"),
    dict(id="blog-safety-epc", category="bugfix", files=["blog/safety-and-certificates/index.html"], expect=(1, 1),
         find="Min. Band E, valid 10 years",
         replace="Valid 10 years, where required"),
    dict(id="handsfree-meta", category="bugfix", files=["platform/hands-free/index.html"], expect=(1, 3),
         find="PropertyFlow's team management tools let you coordinate cleaning, maintenance, and operations from one dashboard. Manage your team, your way.",
         replace="Go fully hands-free: as a 50/50 Partner, PropertyFlow runs cleaning, linen, changeovers, maintenance and compliance for you — you keep guests and growth."),
    dict(id="channels-count", category="bugfix", files=["platform/index.html"], expect=(1, 1),
         find="8 channels live from day one",
         replace="8+ channels live from day one"),
    dict(id="an-availability", category="bugfix", files=["platform/channel-management/index.html"], expect=(1, 1),
         find="a price or an availability once",
         replace="a price or availability once"),
]
