# Spec v3 — factual/legal fixes, remaining pricing strings, UK-wide positioning.
FI = ["for-investors/index.html"]
FL = ["for-landlords/index.html"]
JSO = ["for-landlords/just-starting-out/index.html"]

SPECS = [
    # ═══ factual / legal ═══
    dict(id="fi-licence-transfer", category="bugfix", files=FI, expect=(2, 2),
         find="If you exit STL, the property's planning status and STL licence transfer with it, so future owners have those assets locked in.",
         replace="If you exit STL, planning consent stays with the property; in Scotland a new owner applies for their own STL licence, and an established compliant operation still commands a premium."),

    # ═══ remaining pricing strings ═══
    dict(id="jso-meta-3props", category="pricing", files=JSO, expect=(2, 3),
         find="Start free on your first property",
         replace="Start free on your first three properties"),
    dict(id="jso-cta-1prop", category="pricing", files=JSO, expect=(1, 1),
         find="Start free on 1 property",
         replace="Start free — first 3 properties"),
    dict(id="jso-body-oneprop", category="pricing", files=JSO, expect=(1, 1),
         find="on one property, for as long as you like",
         replace="on up to 3 properties, for as long as you like"),
    dict(id="jso-jsonld-oneprop", category="pricing", files=JSO, expect=(1, 1),
         find="free on one property, for new hosts",
         replace="free on your first three properties, for new hosts"),
    dict(id="bp-tile-5pct", category="pricing", files=["for-landlords/building-a-portfolio/index.html"], expect=(1, 1),
         find='<div class="ds-stat-row__val">5%</div><div class="ds-stat-row__label">Of booking revenue, that\'s it</div>',
         replace='<div class="ds-stat-row__val">First 3</div><div class="ds-stat-row__label">Properties free, forever</div>'),
    dict(id="bp-tile-unlimited", category="pricing", files=["for-landlords/building-a-portfolio/index.html"], expect=(1, 1),
         find='<div class="ds-stat-row__val">Unlimited</div><div class="ds-stat-row__label">Properties, no per-unit fee</div>',
         replace='<div class="ds-stat-row__val">£9.99</div><div class="ds-stat-row__label">Per extra property, per month</div>'),
    dict(id="bp-tile-zero", category="pricing", files=["for-landlords/building-a-portfolio/index.html"], expect=(1, 1),
         find='<div class="ds-stat-row__val">£0</div><div class="ds-stat-row__label">Fixed fees or lock-in</div>',
         replace='<div class="ds-stat-row__val">0%</div><div class="ds-stat-row__label">Airbnb commission &middot; other OTAs 3%</div>'),
    dict(id="nps-free-first-three", category="pricing", files=["for-landlords/new-to-property-software/index.html"], expect=(2, 2),
         find="No, and it's free on your first.",
         replace="No — and it's free on your first three."),

    # ═══ UK-wide positioning ═══
    dict(id="fl-compliance-lead", category="uk-wide", files=FL, expect=(1, 1),
         find="Edinburgh's STL licensing regime is strict, and rising regulation is eliminating non-compliant operators.",
         replace="STL regulation is tightening across the UK — licensing in Scotland, registration on the way in England — and it is eliminating non-compliant operators."),
    dict(id="fl-faq-edinburgh", category="uk-wide", files=FL, expect=(2, 2),
         find="In most Edinburgh cases, yes, tenement flats face high refusal rates under standard planning.",
         replace="It depends on your council. In Edinburgh, for example, tenement flats face high refusal rates under standard planning; other UK authorities run different regimes."),
    dict(id="home-demo-cleaner", category="uk-wide", files=["index.html"], expect=(1, 1),
         find="Cleaner assigned &middot; Edinburgh",
         replace="Cleaner assigned &middot; Glasgow"),
    dict(id="home-demo-booking", category="uk-wide", files=["index.html"], expect=(1, 1),
         find="Edinburgh &middot; &pound;1,240 &middot; 4 nights",
         replace="Manchester &middot; &pound;1,240 &middot; 4 nights"),
    dict(id="fx-demo-payout", category="uk-wide", files=["platform/financials-xero/index.html"], expect=(1, 1),
         find="August payout, Edinburgh",
         replace="August payout, Manchester"),
    dict(id="inbox-demo-flat", category="uk-wide", files=["platform/unified-inbox/index.html"], expect=(1, 1),
         find="Edinburgh flat &middot; Fri&ndash;Tue",
         replace="York flat &middot; Fri&ndash;Tue"),
    dict(id="blog-str-stl", category="uk-wide", files=["blog/index.html"], expect=(2, 3),
         find="UK STR Market Insights",
         replace="UK STL Market Insights"),

    # ═══ terminology / grammar / links ═══
    dict(id="fi-str-market", category="bugfix", files=FI, expect=(1, 2),
         find="UK STR market",
         replace="UK STL market"),
    dict(id="fi-str-yields", category="bugfix", files=FI, expect=(4, 5),
         find="STR yields",
         replace="STL yields"),
    dict(id="fi-on-a-market", category="bugfix", files=FI, expect=(1, 1),
         find="on a market that delivers",
         replace="in a market that delivers"),
    dict(id="fi-valid-licence", category="bugfix", files=FI, expect=(1, 1),
         find="holds valid STL licence",
         replace="holds a valid STL licence"),
    dict(id="fl-user-income-kw", category="bugfix", files=FL, expect=(1, 1),
         find="user income",
         replace="landlord income"),
    dict(id="fl-pf-ops", category="bugfix", files=FL, expect=(1, 1),
         find="These policies cover PF operations, not the landlord's building or contents insurance.",
         replace="These policies cover PropertyFlow's operations; they do not replace your own buildings or contents insurance."),
    dict(id="highlands-link-global", category="bugfix", files=None, expect=(3, 6),
         find='href="/for-landlords/" class="ds-mega__link"><span class="ds-mega__link-title">Highlands &amp; coast</span>',
         replace='href="/for-landlords/highlands-and-coast/" class="ds-mega__link"><span class="ds-mega__link-title">Highlands &amp; coast</span>'),
    dict(id="wwlf-splice-1", category="bugfix", files=["become-a-partner/what-we-look-for/index.html"], expect=(1, 1),
         find="genuine demand, that's what we can grow",
         replace="genuine demand — that's what we can grow"),
    dict(id="wwlf-splice-2", category="bugfix", files=["become-a-partner/what-we-look-for/index.html"], expect=(1, 1),
         find="Apply anyway, we'll be honest",
         replace="Apply anyway — we'll be honest"),
    dict(id="mfo-ms", category="bugfix", files=["for-landlords/managing-for-owners/index.html"], expect=(1, 2),
         find="Ms. Adeyemi",
         replace="Ms Adeyemi"),
    dict(id="mfo-mr", category="bugfix", files=["for-landlords/managing-for-owners/index.html"], expect=(1, 2),
         find="Mr. Osei",
         replace="Mr Osei"),
    dict(id="nps-meta-list", category="bugfix", files=["for-landlords/new-to-property-software/index.html"], expect=(1, 3),
         find="pulls every job you're doing by hand, channels, pricing, messages, compliance, into one login",
         replace="pulls every job you're doing by hand — channels, pricing, messages, compliance — into one login"),
    dict(id="jso-hero-list", category="bugfix", files=JSO, expect=(1, 2),
         find="run the whole thing, channels, pricing, guests and compliance, from one place",
         replace="run the whole thing — channels, pricing, guests and compliance — from one place"),
    dict(id="brand-blog-suffix", category="bugfix", files=None, expect=(1, 20),
         find="— Property Flow Blog</title>",
         replace="— PropertyFlow Blog</title>"),
]
