# Spec v1 — sitewide strings + homepage pricing model correction.
# Categories: bugfix | pricing | uk-wide
H = ["index.html"]

SPECS = [
    # ── sitewide bugfix: broken Newsreader Google Fonts URL (HTTP 400) ──
    dict(id="font-newsreader-url", category="bugfix",
         find="Newsreader:opsz,wght@6..72,0,400;6..72,0,500;6..72,1,400",
         replace="Newsreader:ital,opsz,wght@0,6..72,400;0,6..72,500;1,6..72,400",
         files=None, expect=(58, 58)),

    # ── sitewide nav mega-menu + footer pricing strings ──
    dict(id="mega-pricing-blurb", category="pricing",
         find="Try the PMS free on one property. Run your whole portfolio for 5% of booking revenue. Or become a Partner on a true 50/50 split.",
         replace="Your first 3 properties are free, forever. From your 4th, just £9.99 per extra property per month. Or become a Partner on a true 50/50 split.",
         files=None, expect=(50, 60)),
    dict(id="mega-just-starting", category="pricing",
         find="Your first property, free to run.",
         replace="Your first 3 properties, free to run.",
         files=None, expect=(50, 65)),
    dict(id="footer-tagline", category="pricing",
         find="free to start on your first property.",
         replace="your first 3 properties are always free.",
         files=None, expect=(55, 65)),

    # ── shared meta description sentences (homepage + for-landlords + others) ──
    dict(id="meta-model-sentence", category="pricing",
         find="Start free on one property, scale on Full Management at 5% of booking revenue, or become a 50/50 Partner",
         replace="Your first 3 properties are always free, then just £9.99 per extra property per month — or go hands-free as a 50/50 Partner",
         files=None, expect=(2, 12)),
    dict(id="meta-model-twitter", category="pricing",
         find="Start free on one property, Full Management at 5%, or a 50/50 Partner model",
         replace="First 3 properties always free, £9.99 per extra property after that, or a 50/50 Partner model",
         files=None, expect=(1, 6)),

    # ── homepage JSON-LD ──
    dict(id="jsonld-pricerange", category="pricing",
         find='"priceRange": "Free Get Started, Full Management 5% of revenue, Partner 50/50"',
         replace='"priceRange": "Free (first 3 properties), Premium £9.99 per extra property per month, Partner 50/50"',
         files=None, expect=(1, 4)),
    dict(id="jsonld-faq-threeways", category="pricing",
         find="Get Started is free for a single property. Full Management is 5% of booking revenue across unlimited properties with no fixed fees.",
         replace="The Free plan gives you the full platform on up to 3 properties, forever. Premium starts from your 4th property at just £9.99 per extra property per month — Airbnb bookings at 0% commission, other OTAs at 3%.",
         files=None, expect=(1, 3)),

    # ── homepage hero chips ──
    dict(id="chip-start", category="pricing",
         find='<div class="ds-chip__label">Start on 1 property</div>',
         replace='<div class="ds-chip__label">First 3 properties free</div>',
         files=H, expect=(1, 1)),
    dict(id="chip-premium", category="pricing",
         find='<div class="ds-chip__value">5%</div>\n                    <div class="ds-chip__label">Full Management, unlimited</div>',
         replace='<div class="ds-chip__value">£9.99</div>\n                    <div class="ds-chip__label">Per extra property, from your 4th</div>',
         files=H, expect=(1, 1)),

    # ── homepage plans section ──
    dict(id="plans-lead", category="pricing",
         find="From a free single-property trial to a full 50/50 operational partnership",
         replace="From your first three properties free to a full 50/50 operational partnership",
         files=H, expect=(1, 1)),
    dict(id="tier1-name", category="pricing",
         find='<h3 class="ds-tier__name">Get Started</h3>',
         replace='<h3 class="ds-tier__name">Free</h3>',
         files=H, expect=(1, 1)),
    dict(id="tier1-sub", category="pricing",
         find='<p class="ds-tier__sub">Try the PMS on one property</p>',
         replace='<p class="ds-tier__sub">For solo hosts · 1–3 properties</p>',
         files=H, expect=(1, 1)),
    dict(id="tier1-price", category="pricing",
         find='<div class="ds-tier__price">Free <span>/ 1 property</span></div>',
         replace='<div class="ds-tier__price">£0 <span>/ month, forever</span></div>',
         files=H, expect=(1, 1)),
    dict(id="tier1-commission-li", category="pricing",
         find='<li><span class="ds-tier__tick">✓</span>Unified guest inbox</li>\n                    <li><span class="ds-tier__tick">✓</span>Compliance tracking</li>',
         replace='<li><span class="ds-tier__tick">✓</span>Unified guest inbox</li>\n                    <li><span class="ds-tier__tick">✓</span>Compliance tracking</li>\n                    <li><span class="ds-tier__tick">✓</span>Airbnb 0% · other OTAs 5% commission</li>',
         files=H, expect=(1, 1)),
    dict(id="tier2-name", category="pricing",
         find='<h3 class="ds-tier__name">Full Management</h3>',
         replace='<h3 class="ds-tier__name">Premium</h3>',
         files=H, expect=(1, 1)),
    dict(id="tier2-sub", category="pricing",
         find='<p class="ds-tier__sub">Run everything yourself on the PMS</p>',
         replace='<p class="ds-tier__sub">For multi-property portfolios · 4+ properties</p>',
         files=H, expect=(1, 1)),
    dict(id="tier2-price", category="pricing",
         find='<div class="ds-tier__price">5% <span>of booking revenue</span></div>',
         replace='<div class="ds-tier__price">£9.99 <span>/ extra property / month</span></div>',
         files=H, expect=(1, 1)),
    dict(id="tier2-note", category="pricing",
         find='<p class="ds-tier__note">As many properties as you like, pay only when you earn</p>',
         replace='<p class="ds-tier__note">Your first 3 always free · auto-upgrades only when needed</p>',
         files=H, expect=(1, 1)),
    dict(id="tier2-commission-li", category="pricing",
         find='<li><span class="ds-tier__tick">✓</span>As many properties as you like</li>',
         replace='<li><span class="ds-tier__tick">✓</span>As many properties as you like</li>\n                    <li><span class="ds-tier__tick">✓</span>Airbnb 0% · other OTAs 3% (saves 2%)</li>',
         files=H, expect=(1, 1)),
    dict(id="tier2-cta", category="pricing",
         find=">Choose Full Management</a>",
         replace=">Choose Premium</a>",
         files=None, expect=(1, 4)),
    dict(id="everything-in-getstarted", category="pricing",
         find="Everything in Get Started</li>",
         replace="Everything in Free</li>",
         files=None, expect=(1, 4)),
    dict(id="everything-in-fm", category="pricing",
         find="Everything in Full Management</li>",
         replace="Everything in Premium</li>",
         files=None, expect=(1, 4)),

    # ── homepage how-it-works steps ──
    dict(id="steps-lead", category="pricing",
         find="Begin on a single property, grow into a portfolio",
         replace="Begin with up to three properties free, grow into a portfolio",
         files=H, expect=(1, 1)),
    dict(id="step1-title", category="pricing",
         find='<div class="ds-card__title">Start free on one property</div>',
         replace='<div class="ds-card__title">Start free — first 3 properties</div>',
         files=H, expect=(1, 1)),
    dict(id="step1-text", category="pricing",
         find="Create your account, add a single property, and explore the full PMS. No card required — it is the fastest way to get a feel for the platform.",
         replace="Create your account, add up to three properties, and explore the full PMS. No card required — it is the fastest way to get a feel for the platform.",
         files=H, expect=(1, 1)),
    dict(id="step2-title", category="pricing",
         find='<div class="ds-card__title">Scale on Full Management</div>',
         replace='<div class="ds-card__title">Scale on Premium</div>',
         files=H, expect=(1, 1)),
    dict(id="step2-text", category="pricing",
         find="Add as many properties as you like and run the whole portfolio yourself on the PMS for just 5% of booking revenue. No fixed fees — you pay only when you earn.",
         replace="From your 4th property it is just £9.99 per extra property per month — your first 3 stay free. Airbnb bookings carry 0% commission and other OTAs just 3%.",
         files=H, expect=(1, 1)),

    # ── homepage testimonials plan tags ──
    dict(id="quote-tier-tag", category="pricing",
         find="<span>Full Management · ",
         replace="<span>Premium · ",
         files=H, expect=(3, 3)),

    # ── homepage FAQ ──
    dict(id="faq-threeways-body", category="pricing",
         find="There are three ways to work with us. Get Started is free for a single property — a trial account to get the feel of the PMS. Full Management gives you the full platform across as many properties as you like for 5% of booking revenue, with no fixed or per-property fees. Become a Partner is a true 50/50 partnership:",
         replace="There are three ways to work with us. The Free plan gives you the full platform on up to 3 properties — free forever, with Airbnb at 0% commission and other OTAs at 5%. Premium starts from your 4th property at just £9.99 per extra property per month, and drops other-OTA commission to 3%. Become a Partner is a true 50/50 partnership:",
         files=H, expect=(1, 1)),
    dict(id="faq-free-summary", category="pricing",
         find="What is included in the free Get Started plan?",
         replace="What is included in the Free plan?",
         files=None, expect=(1, 3)),
    dict(id="faq-free-body", category="pricing",
         find="Full access to the PMS on one property:",
         replace="Full access to the PMS on up to 3 properties:",
         files=None, expect=(1, 3)),
    dict(id="faq-premium-summary", category="pricing",
         find="What does Full Management cost?",
         replace="What does Premium cost?",
         files=None, expect=(1, 3)),
    dict(id="faq-premium-body", category="pricing",
         find="Full Management is 5% of booking revenue with no fixed fees and no per-property charge. You can add as many properties as you like and you only pay when a booking earns. You run the portfolio yourself using the full PMS, with financials and Xero sync, team and cleaner management, and priority support included.",
         replace="Premium is £9.99 per extra property per month from your 4th property — your first 3 stay free. Airbnb bookings carry 0% commission and other OTAs just 3%. You run the portfolio yourself using the full PMS, with financials and Xero sync, team and cleaner management, and priority support included.",
         files=None, expect=(1, 2)),
    dict(id="faq-move-body", category="pricing",
         find="Most operators start free on one property, move to Full Management as they add more, and apply to become a Partner",
         replace="Most operators start on the Free plan, upgrade to Premium as they grow past three properties, and apply to become a Partner",
         files=None, expect=(1, 3)),
    dict(id="typo-lockin-comma", category="bugfix",
         find="no lock-in ,change",
         replace="no lock-in — change",
         files=None, expect=(1, 3)),
    dict(id="faq-channels-getstarted", category="pricing",
         find="including the free Get Started account",
         replace="including the Free plan",
         files=None, expect=(1, 3)),
]
