# Spec v5 — Edinburgh-market/licensing-guide fixes, landlord→"user" artefacts, legal titles, typography.
LG = ["edinburgh-market/stl-licensing-guide/index.html"]
EM = ["edinburgh-market/index.html"]
PD = ["edinburgh-market/pricing-data/index.html"]
CL = ["blog/corporate-let-vs-managed-service/index.html"]

SPECS = [
    dict(id="em-cta-3props", category="pricing", files=EM, expect=(1, 1),
         find="free to try on your first property",
         replace="free to try on your first three properties"),
    dict(id="em-realtime", category="bugfix", files=EM, expect=(3, 3),
         find="Real-time market intelligence",
         replace="Up-to-date market intelligence"),
    dict(id="em-users-jsonld", category="bugfix", files=EM, expect=(1, 1),
         find="licensing information for users and investors",
         replace="licensing information for operators and investors"),
    dict(id="lg-fee-model", category="pricing", files=LG, expect=(1, 1),
         find="PropertyFlow's fee (5%) is competitive when you consider the compliance guarantee and zero-gap strategy.",
         replace="PropertyFlow's pricing (first 3 properties free, then £9.99 per extra property per month — or a 50/50 Partner split) is competitive when you consider the compliance guarantee and zero-gap strategy."),
    dict(id="lg-planning-fee", category="bugfix", files=LG, expect=(2, 2),
         find="~£401 (planning application fee)",
         replace="~£600+ (planning application fee — check the current City of Edinburgh Council rate)"),
    dict(id="lg-7days", category="bugfix", files=LG, expect=(1, 1),
         find="owner must be present on the property at least 7 days per week",
         replace="owner must live at the property as their principal home"),
    dict(id="lg-home-letting", category="bugfix", files=LG, expect=(1, 1),
         find="must own at least one other property that serves as their primary residence.",
         replace="lets their own primary residence while temporarily away (for example for work or travel)."),
    dict(id="lg-users-1", category="bugfix", files=LG, expect=(1, 1),
         find="For users or investors letting properties",
         replace="For landlords or investors letting properties"),
    dict(id="lg-users-2", category="bugfix", files=LG, expect=(1, 1),
         find="User's Insurance policy",
         replace="Landlord insurance policy"),
    dict(id="lg-users-3", category="bugfix", files=LG, expect=(1, 1),
         find="Standard user insurance does NOT cover STL",
         replace="Standard landlord insurance does NOT cover STL"),
    dict(id="lg-licenses", category="bugfix", files=LG, expect=(1, 1),
         find="Old licenses don't",
         replace="Old licences don't"),
    dict(id="vl-user-artefact", category="bugfix", files=["blog/edinburgh-visitor-levy/index.html"], expect=(1, 1),
         find="The visitor -- not the user -- pays the levy",
         replace="The visitor — not the operator — pays the levy"),
    dict(id="cl-users-1", category="bugfix", files=CL, expect=(1, 1),
         find="Edinburgh users ask when exploring",
         replace="Edinburgh landlords ask when exploring"),
    dict(id="cl-users-2", category="bugfix", files=CL, expect=(1, 1),
         find="the type of user each model",
         replace="the type of landlord each model"),
    dict(id="cl-users-3", category="bugfix", files=CL, expect=(1, 1),
         find="ideal for users who want complete predictability",
         replace="ideal for landlords who want complete predictability"),
    dict(id="privacy-form-users", category="bugfix", files=["privacy-policy.html"], expect=(1, 1),
         find="user, investor, developer, agent, or other",
         replace="landlord, investor, developer, agent, or other"),
    dict(id="privacy-title-brand", category="bugfix", files=["privacy-policy.html"], expect=(1, 1),
         find="<title>Privacy Policy — Property Flow Technologies Ltd",
         replace="<title>Privacy Policy — PropertyFlow Technologies Ltd"),
    dict(id="terms-title-brand", category="bugfix", files=["terms.html"], expect=(1, 1),
         find="<title>Terms of Service — Property Flow Technologies Ltd",
         replace="<title>Terms of Service — PropertyFlow Technologies Ltd"),
    dict(id="blog-licenced", category="bugfix", files=["blog/index.html"], expect=(1, 1),
         find="licenced properties command",
         replace="licensed properties command"),
    dict(id="pd-maximizing", category="bugfix", files=PD, expect=(1, 1),
         find="maximizing", replace="maximising"),
    dict(id="pd-maximize", category="bugfix", files=PD, expect=(1, 1),
         find="maximize", replace="maximise"),
    dict(id="pd-optimizes", category="bugfix", files=PD, expect=(1, 1),
         find="optimizes", replace="optimises"),
    dict(id="pd-bruntsfield-rate", category="bugfix", files=PD, expect=(1, 1),
         find='<td class="ds-table__cell ds-table__label">Bruntsfield</td>\n                                <td class="ds-table__cell">2-Bed</td>\n                                <td class="ds-table__cell">£180</td>',
         replace='<td class="ds-table__cell ds-table__label">Bruntsfield</td>\n                                <td class="ds-table__cell">2-Bed</td>\n                                <td class="ds-table__cell">£145</td>'),
    dict(id="aip-holiday-let", category="bugfix", files=["platform/ai-pricing/index.html"], expect=(3, 3),
         find="holiday let revenue",
         replace="short-term let revenue"),
    dict(id="levy-date-anchor", category="bugfix", files=None, expect=(8, 12),
         find="Before July 2026",
         replace="Before 24 July 2026"),
    dict(id="double-hyphen-dash", category="bugfix", files=None, expect=(30, 60),
         find=" -- ",
         replace=" — "),
]
