# Spec v6 — final stragglers.
FL = ["for-landlords/index.html"]

SPECS = [
    dict(id="pl-jsonld-cognito-lc", category="bugfix", files=["platform/index.html"], expect=(1, 1),
         find="Cognito pricing, compliance tracking",
         replace="Smart Pricing, compliance tracking"),
    dict(id="vl-cognito-lc", category="bugfix", files=["blog/edinburgh-visitor-levy/index.html"], expect=(1, 1),
         find="<strong>Cognito pricing adjustment:</strong>",
         replace="<strong>Smart Pricing adjustment:</strong>"),
    dict(id="fl-tier1-name", category="pricing", files=FL, expect=(1, 1),
         find='<p class="ds-tier__name">Get Started</p>',
         replace='<p class="ds-tier__name">Free</p>'),
    dict(id="fl-tier1-price", category="pricing", files=FL, expect=(1, 1),
         find='<p class="ds-tier__price">Free <span>/ 1 property</span></p>',
         replace='<p class="ds-tier__price">£0 <span>/ month, forever</span></p>'),
    dict(id="fl-tier1-sub", category="pricing", files=FL, expect=(1, 1),
         find="A trial account to get the feel of the PMS. Full platform access on a single property — every channel, AI pricing, unified inbox and compliance tracking.",
         replace="The full platform on up to 3 properties, forever — every channel, AI pricing, unified inbox and compliance tracking. Airbnb 0% commission, other OTAs 5%."),
    dict(id="fl-tier2-name", category="pricing", files=FL, expect=(1, 1),
         find='<p class="ds-tier__name">Full Management</p>',
         replace='<p class="ds-tier__name">Premium</p>'),
    dict(id="fl-tier2-price", category="pricing", files=FL, expect=(1, 1),
         find='<p class="ds-tier__price">5% <span>of booking revenue</span></p>',
         replace='<p class="ds-tier__price">£9.99 <span>/ extra property / month</span></p>'),
    dict(id="fl-tier2-note", category="pricing", files=FL, expect=(1, 1),
         find='<p class="ds-tier__note">Unlimited properties · pay only when you earn</p>',
         replace='<p class="ds-tier__note">First 3 always free · Airbnb 0%, other OTAs 3%</p>'),
    dict(id="fl-tier2-sub", category="pricing", files=FL, expect=(1, 1),
         find="Run your whole portfolio yourself on the PMS. Add as many properties as you like with no fixed fees — financials and team management included.",
         replace="Run your whole portfolio yourself on the PMS. From your 4th property it is £9.99 per extra property per month — financials and team management included."),
    dict(id="bp-jsonld-name", category="pricing", files=["for-landlords/building-a-portfolio/index.html"], expect=(1, 1),
         find='"PropertyFlow Full Management for Growing Portfolios"',
         replace='"PropertyFlow Premium for Growing Portfolios"'),
    dict(id="p-partner-li", category="pricing", files=["pricing/index.html"], expect=(1, 1),
         find="Everything in Full Management",
         replace="Everything in Premium"),
    dict(id="p-comment", category="pricing", files=["pricing/index.html"], expect=(1, 1),
         find="<!-- FULL MANAGEMENT -->",
         replace="<!-- PREMIUM -->"),
    dict(id="lg-401-bare", category="bugfix", files=["edinburgh-market/stl-licensing-guide/index.html"], expect=(1, 1),
         find="£401",
         replace="£600+"),
]
